# Generated by Django 4.1.7 on 2023-04-13 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_toy_capybara_toys'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='capybara',
            name='toys',
        ),
    ]
